### ISSUE TITLE
Consider supporting regex

### ISSUE THREAD

**Issue by lohmander** [team-boris/redux-effects-fetch-fixture#10]
Hey, I just wanted to see if there's any intention to add support for regex, or some sort of parameterized, paths?

I realise this adds some complexity but should be fairly easy to do. I'm willing to give it a shot if it's inline with what you want to do.

**Comment by muuki88** [comment]
Hi @lohmander :smile: 

Thanks for your feature request. Indeed we were thinking about adding regex support, but there was no need for us. If you would like to open a pull request I'm more than happy to review and merge :heart_eyes:
