### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by swsnr** [team-boris/redux-effects-fetch-fixture#5]

**Comment by muuki88** [comment]
Done: https://www.npmjs.com/package/redux-effects-fetch-fixture

Publishing is pretty easy:

```
npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease | from-git] 
npm publish
```

see:
- https://docs.npmjs.com/getting-started/publishing-npm-packages
- https://docs.npmjs.com/misc/developers

@lunaryorn do you have a npmjs account? I'll add you as a collaborator.
